# -*- coding: utf-8 -*-
"""diffusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTCuRowqxeANmRXoel99V8UVUjQ_M3DJ
"""

!pip install diffusers transformers accelerate scipy

from diffusers import DiffusionPipeline
import torch


pipe = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipe.to("cuda")


prompt = "Unicorn through rainbow flowers and cloud, highly detailed, cinematic lighting, 8k"


generator = torch.Generator("cuda").manual_seed(42)
image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5, generator=generator).images[0]


image